###  GET ALL USERS ###
GET http://localhost:3200/api/users

### CREATE NEW USER ###

POST http://localhost:3200/api/users
Content-Type: application/json

{
  "username": "junedev",
  "email": "junedev@june.dev",
  "password": "lajunepassword"
}